chore: if failed to enable code dumps, ignore it

diff --git a/postgres-appliance/runit/patroni/run b/postgres-appliance/runit/patroni/run
--- a/postgres-appliance/runit/patroni/run
+++ b/postgres-appliance/runit/patroni/run
@@ -17,8 +17,8 @@ then
     echo "Failed to enable coredump shared memory filter"
 fi
 
-# Enable core dumps
-ulimit -c unlimited
+# Enable core dumps, if return code is not 0, just ignore it
+ulimit -c unlimited || true
 
 # Only small subset of environment variables is allowed. We don't want accidentally disclose sensitive information
 for E in $(printenv -0 | tr '\n' ' ' | sed 's/\x00/\n/g' | grep -vE '^(KUBERNETES_(SERVICE|PORT|ROLE)[_=]|((POD_(IP|NAMESPACE))|HOSTNAME|PATH|PGHOME|LC_ALL|ENABLE_PG_MON)=)' | sed 's/=.*//g'); do
